//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinServiceCrawler
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public int id { get; set; }
        public Nullable<long> postID { get; set; }
        public Nullable<int> countOfComments { get; set; }
        public Nullable<int> likes { get; set; }
        public string text { get; set; }
        public Nullable<int> reposts { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    }
}
